### PR TITLE
set FirstRun so Plex doesn't spawn a hidden browser window

### PR DESCRIPTION
**Pull request by 3van**
Firefox, et al. complain about already being active otherwise when first trying to start them.

I suppose it may make sense to spawn a browser pointing to the setup URL using the tray application if the service has to set this key.

### CODE REVIEW

**Comment by sa2000a** [comment]
I have not looked at the change but this needs to be for the local user account the service runs in and not the user account the install is being run in

For the user the install is being run in, s welcome change would be deleting the entry for auto launch of plsx media server in 'Run'

**Comment by 3van** [comment]
@sa2000a: that's exactly what it does; the code I added was to PlexServiceWCF and runs as part of the service start routines (before PMS actually gets spawned).

I could add an option to the installer to remove the PMS entry from the install user's Run key if it's present; that seems reasonable. There's already a function that runs (before the one I added) that removes the autostart key for the service user. In a big chunk of use cases, I'd imagine the service will be running as the install user, so that gets taken care of automatically.

**Comment by sa2000a** [comment]
@3van - thank you for confirming what the change does.
With regards to the change for `Run` - I do not think what i want is achievable as the change to the installer would not be sufficient. The deletion needs to be done after every install of Plex Media Server. And at run time we cannot do it, because it would need admin elevation.

**Comment by cjmurph** [comment]
@sa2000a The service already removes the run key. Is this not working for you?

**Comment by sa2000a** [comment]
@cjmurph - No,  it is not sufficient for me.  

I need it removing from the install account - so I do a Regedit after every install of a new plex media server version. It cannot be done within the service because the service runs in a non-admin account and would not have rights to delete a key in the admin account registry.

I will have to put up with this until the Plex Media Server install process changes to give an option for auto-launch that one can untick

**Comment by cjmurph** [comment]
It could be done, I could change the permission on the registry key parent for all user hives I can find during install then attempt removal from all user hives when starting the service. maybe.

**Comment by sa2000a** [comment]
Thank you. Yes, that would work but that would break security rules - unless it is made an option and user can confirm would be happy with such action.

That would save me having to edit the registry everytime

**Comment by cjmurph** [comment]
The other option is that when you install you start once and uncheck the start with windows option in the pms tray icon. maybe this issue is outside the scope of the service. Have you requested an installer change on the plex forums?

**Comment by sa2000a** [comment]
Don't remember if I have asked. It is safer for me to stick with the regedit rather than launching the program and unticking - don't want to have any code to do with listening to ports or broadcasts or declaring the server MachineIdentifier to be executed.

**Comment by cjmurph** [comment]
if you launch it, it will start with the current user library/settings. If that's not the same as the library/settings used when it starts as a service, it'll be like a fresh install with no library or sections.

Safest to just change the registry. If I were you I'd just write a quick script to do the registry change rather than do it manually every time.

**Comment by 3van** [comment]
Just to make sure there wasn't a 'hidden' option you could pass to the PMS installer to prevent it from autostarting, I decompiled the PMS setup package and looked at the WiX for it; there is no way to prevent it from adding Plex to the install user's Run key. It gets added as part of the `PlexMediaServerShortcuts` component, which is always part of the main `Plex` feature that gets installed.

**Pull request merged**
